### ISSUE TITLE
TypeError: non-default argument 'name' follows default argument

### ISSUE THREAD

**Issue by mardukbp** [MarketSquare/robotframework-openapi-libcore#11]
Minimal Failing Example

```robotframework
*** Settings ***
Library    OpenApiLibCore
...        source=https://petstore3.swagger.io/api/v3/openapi.json
...        origin=https://petstore3.swagger.io
...        base_path=/api/v3

*** Test Cases ***
Get Request Data
    Get Request Data    endpoint=/pet   method=post
```

I believe there is an error in the code that generates the dataclasses from the schemas in the specification. Maybe it would be better to use [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator) for this purpose.

-----
robot --version
Robot Framework 6.0.2 (Python 3.8.10 on win32)

**Comment by robinmackaij** [comment]
Thanks for reporting! The needed fix was actually in the fields list that is used to generate dataclasses at runtime. In the openapi from the petstore, the required properties are not listed before optional properties.

datamodel-code-generator looks interesting, but from a quick glance, I cannot use it since I generate dataclasses at runtime based on the Dto classes that are user-defined in the mappings file that I support.
